### ISSUE TITLE
How to build & run this?

### ISSUE THREAD

**Issue by xxczaki** [Haeri/Monolith-Code-Legacy#2]
???

**Comment by Haeri** [comment]
I don't provide any specific project files so this project can be compiled with any IDE. Therefore you have to create your own project and import all the files into your IDE of choice. Also I am using a few libraries, which are located in the `external`, so you have to also add them in your project settings.

I use Eclipse, so here is how you can set it up with Eclipse:
1. Create a new Project:
New -> Project -> Java Project -> (call the project whatever you want) -> Finish.
2. Import the repository:
Import -> File System -> Browse -> (select the downloaded repository folder) -> Select All -> Browse Folder -> (select the previously created project) -> Finish.
3. Set up the external libraries:
Properties -> Java Build Path -> Add External Jars -> (select all files inside external) -> Apply

This should be all :D
