### ISSUE TITLE
How to run the file/ how to launch the application?/website is not opening.

### ISSUE THREAD

**Issue by ghrahul** [Haeri/Monolith-Code-Legacy#4]

**Comment by Haeri** [comment]
To compile the source code by yourself, you will need to set up a project with your preferred Java IDE. See [this issue](https://github.com/Haeri/Monolith-Code/issues/2#issuecomment-318930937), where I explain how to set it up with eclipse.

You can download the latest jar files from the website. Just double-click the "Monolith.jar" executable to launch the application. (obviously need to have java installed).

The website seems to be working fine.

Hope this helps.

**Comment by ghrahul** [comment]
official website is still not working.

**Comment by ghrahul** [comment]
![screenshot 30](https://user-images.githubusercontent.com/22416933/45119738-dfe0a200-b179-11e8-852b-e80ba3084f8d.png)


-- after running the project the ui is showing like this.

**Comment by Haeri** [comment]
I really don't know what to tell you. The website is up. I can access it with any browser. I also did a quick "is it up" test. Seems to be working fine. 

![screenshot_2](https://user-images.githubusercontent.com/7956606/45124764-d81a0100-b16b-11e8-802f-a0f87142f8f9.png)
![screenshot_4](https://user-images.githubusercontent.com/7956606/45124767-dc461e80-b16b-11e8-93c5-d3a11b08ec67.png)


The UI you are seeing is from the "RSyntaxTextArea.jar". So you are basically running one of the dependency and not the main application. You need to right-click on the "Monolith-Code/src/main/java/net/monolith/Main.java" file and execute from there.
